import "../styles/globals.css"

import type { Metadata } from "next"

import { nanumSquareNeo } from "@/lib/assets/fonts/fonts"
import { ThemeProvider } from "@/components/utils/ThemeProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="ko" suppressHydrationWarning>
        <head />
        <body className={nanumSquareNeo.variable}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
