import "../styles/globals.css"

import type { Metadata } from "next"

import { fonts } from "@/lib/fonts/fonts"
import { cn } from "@/lib/utils"
import { Layout } from "@/components/Layout/Layout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn(fonts.pretendard.variable)}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
