import "../styles/globals.css"

import type { Metadata } from "next"
import { getServerSession } from "next-auth"

import { fonts } from "@/lib/fonts"
import { SessionProvider } from "@/components/@provider/session-provider"
import { Shell } from "@/components/shell"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={`${fonts.pretendard.variable} ${fonts.tenada.variable}`}>
        <SessionProvider session={session}>
          <Shell>{children}</Shell>
        </SessionProvider>
      </body>
    </html>
  )
}
