import "../styles/globals.css"

import type { Metadata } from "next"

import { fonts } from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${fonts.pretendard.variable} ${fonts.tenada.variable}`}>
        {children}
      </body>
    </html>
  )
}
